# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slup',
            new_name='slug',
        ),
    ]
